apiVersion: baremetal.cluster.gke.io/v1
kind: Cluster
metadata:
  name: edge-hardened-cluster
  namespace: cluster-edge-prod
spec:
  type: user
  profile: secure-by-default-extended
  kubernetesVersion: 1.28.0
  controlPlane:
    nodePoolSpec:
      nodes:
      - address: 10.200.1.10
  nodeAccess:
    sshPrivateKeyPath: /var/keys/id_rsa_hardened
  osEnvironment:
    operatingSystem: RHEL
    auditdLogging: true
  clusterNetwork:
    flatMode: false
    ports:
      kubeletReadOnlyPort: 0
