apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: secure-gpu-cluster-queue
spec:
  namespaceSelector: {}
  cohort: secure-ai-cohort
  resourceGroups:
  - flavors:
    - name: h100-gpu-flavor
    resources:
    - name: "nvidia.com/gpu"
      nominalQuota: 8
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: secure-gpu-local-queue
  namespace: ai-inference
spec:
  clusterQueue: secure-gpu-cluster-queue

# created by @jsaccomani
