apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: payments-processing
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

# created by @jsaccomani
