apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockLatestTag
metadata:
  name: enforce-image-digests-only
spec:
  enforcementAction: deny
  match:
    namespaces:
    - payments-processing
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]

# created by @jsaccomani
