apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gke-security-hardening-baseline
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/g-jsaccomani/gkesecurity.git'
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: payments-processing
  syncPolicy:
    automated:
      prune: true     # Automatically removes untracked resources
      selfHeal: true  # Instantly overwrites manual hot-fixes inside the cluster
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
